application: cloud-training-144023
version: aplha001
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /images/.*
  static_dir: https://storage.googleapis.com/apppics/

- url: /.*
  script: main.app

libraries:
- name: jinja2
  version: latest
