application: cloud-training-144023
version: aplha001
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /images/.*
  static_dir: https://storage.googleapis.com/apppics/
  secure: always
  login: required

- url: /.*
  script: main.app
  secure: always
  login: required
